spring.application.name=convivials
spring.datasource.url=jdbc:postgresql://localhost:5432/gymconvivals
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true

spring.security.user.name=Rohith
spring.security.user.password=Password
jwt.key=bXktc3VwZXItc2VjdXJlLXN1cGVyLXNlY3VyZS1zdXBlci1zZWNyZXQ=
cloudflare.tokenValue=x3XZzS2emlRBIMz9bUHJO0Yq_HTMPHV3baluHijL
cloudflare.accessKeyID=d6ad9f8d4f3187f46c42c42b90dd5797
cloudflare.secretAccessKey=6edd8a2d72187c108418854909740ad6ad20f3443e4bdba553c1c27edbe1abc9
cloudflare.endpoint=https://9a1c7e3605a62549d5915800bcdbbdf4.r2.cloudflarestorage.com
cloudflare.accountId=9a1c7e3605a62549d5915800bcdbbdf4
cloudflare.bucket=user-media