name: conditons-demo
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.ref_name=='master'
        run: echo "Hi Master!"
      - name: step2
        if: github.ref_name=='postcontroller'
        run: echo "Hi Post controller!"
